pipeline:
  test:
    group: build
    image: python:3.6.3
    commands:
      - pip install -r requirements.txt
      - coverage run test.py
      - codecov
    secrets: [ codecov_token ]
    
  build:
    group: build
    image: plugins/docker
    repo: no0dles/kubemonitor
    dry_run: true
    
  publish:
    image: plugins/docker
    repo: no0dles/kubemonitor
    tags: "${DRONE_TAG}"
    secrets: [ docker_username, docker_password ]
    when:
      event: tag
