pipeline:
  test:
    image: python:3.6.3
    commands:
      - pip install -r requirements.txt
      - coverage run test.py
      - bash <(curl -s https://codecov.io/bash)

  publish:
    image: plugins/docker
    repo: no0dles/kubemonitor
    tags: "${DRONE_TAG}"
    secrets: [ docker_username, docker_password ]
    when:
      event: tag