pipeline:
  test:
    image: python:3.6.3
    commands:
      - python test.py

  publish:
    image: plugins/docker
    repo: no0dles/kubemonitor
    tags: "${DRONE_TAG}"
    secrets: [ docker_username, docker_password ]
    when:
      event: tag